#!/usr/bin/env bash
# scripts/docs/generate-metrics-report.sh
#
# Generate a documentation metrics report
# Part of living documentation automation

set -e

# Colors for output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

REPORT_FILE="DOCS/metrics-report.md"
REPORT_DATE=$(date +"%Y-%m-%d")

echo "=== Generating Documentation Metrics Report ==="
echo ""

# Start report
cat > "$REPORT_FILE" << EOF
# Documentation Metrics Report

**Generated:** $REPORT_DATE
**Repository:** iOS Health Sync

---

## Summary

EOF

# Count total markdown files
total_files=$(find DOCS -name "*.md" -type f | wc -l)
echo "Total documentation files: $total_files" | tee -a "$REPORT_FILE"

# Count words
total_words=$(find DOCS -name "*.md" -type f -exec cat {} \; | wc -w | tr -d ' ')
echo "Total word count: $total_words" | tee -a "$REPORT_FILE"

# Count code examples
code_blocks=$(find DOCS -name "*.md" -type f -exec grep -c '```' {} \; | awk '{sum+=$1} END {print sum}')
code_examples=$((code_blocks / 2)) # Each code block has opening and closing
echo "Code examples: $code_examples" | tee -a "$REPORT_FILE"

echo "" | tee -a "$REPORT_FILE"

# Documentation by section
echo "## Documentation by Section" | tee -a "$REPORT_FILE"
echo "" | tee -a "$REPORT_FILE"

for section in learn how-to reference tutorials explanation; do
    if [ -d "DOCS/$section" ]; then
        count=$(find "DOCS/$section" -name "*.md" -type f | wc -l | tr -d ' ')
        words=$(find "DOCS/$section" -name "*.md" -type f -exec cat {} \; | wc -w | tr -d ' ')
        echo "- **$section**: $count files, $words words" | tee -a "$REPORT_FILE"
    fi
done

echo "" | tee -a "$REPORT_FILE"

# Largest files
echo "## Top 10 Largest Files (by word count)" | tee -a "$REPORT_FILE"
echo "" | tee -a "$REPORT_FILE"

find DOCS -name "*.md" -type f -exec sh -c 'echo "$(wc -w < "$1") $1"' _ {} \; | \
    sort -rn | head -10 | while read -r count file; do
    filename=$(basename "$file")
    echo "1. **$filename**: $count words" | tee -a "$REPORT_FILE"
done

echo "" | tee -a "$REPORT_FILE"

# Recently updated
echo "## Recently Updated (Last 7 Days)" | tee -a "$REPORT_FILE"
echo "" | tee -a "$REPORT_FILE"

find DOCS -name "*.md" -type f -mtime -7 -printf "%TY-%Tm-%Td %p\n" | \
    sort -r | head -10 | while read -r date file; do
    filename=$(basename "$file")
    echo "- $date: **$filename**" | tee -a "$REPORT_FILE"
done

echo "" | tee -a "$REPORT_FILE"

# Sections completeness
echo "## Documentation Coverage" | tee -a "$REPORT_FILE"
echo "" | tee -a "$REPORT_REPORT"

check_section() {
    local section="$1"
    local required_files="$2"

    echo "### $section" | tee -a "$REPORT_FILE"

    for file in $required_files; do
        if [ -f "DOCS/$section/$file" ]; then
            echo -e "  ${GREEN}✓${NC} $file" | tee -a "$REPORT_FILE"
        else
            echo -e "  ${YELLOW}✗${NC} $file (missing)" | tee -a "$REPORT_FILE"
        fi
    done

    echo "" | tee -a "$REPORT_FILE"
}

# Check key documentation files
echo "## Key Documentation Files" | tee -a "$REPORT_FILE"
echo "" | tee -a "$REPORT_FILE"

key_files=(
    "README.md:Main README"
    "QUICKSTART.md:Quick Start Guide"
    "TROUBLESHOOTING.md:Troubleshooting Guide"
    "VERSIONS.md:Version Requirements"
    "ACCESSIBILITY.md:Accessibility Guide"
    "CONTRIBUTING.md:Contributing Guide"
    "METRICS.md:Metrics Guide"
)

for entry in "${key_files[@]}"; do
    file="${entry%%:*}"
    name="${entry##*:}"

    if [ -f "DOCS/$file" ]; then
        words=$(wc -w < "DOCS/$file" | tr -d ' ')
        echo -e "${GREEN}✓${NC} **$name**: $words words" | tee -a "$REPORT_FILE"
    else
        echo -e "${YELLOW}✗${NC} **$name**: (missing)" | tee -a "$REPORT_FILE"
    fi
done

echo "" | tee -a "$REPORT_FILE"

# Orphaned files (not linked from anywhere)
echo "## Potentially Orphaned Files" | tee -a "$REPORT_FILE"
echo "" | tee -a "$REPORT_FILE"
echo "Files not linked from other documentation:" | tee -a "$REPORT_FILE"
echo "" | tee -a "$REPORT_FILE"

for file in $(find DOCS -name "*.md" -type f); do
    filename=$(basename "$file")
    # Count how many files link to this one
    links=$(grep -rl "$filename" DOCS --include="*.md" | wc -l | tr -d ' ')

    if [ "$links" -eq 0 ] && [[ ! "$filename" =~ ^README ]]; then
        echo "- $filename" | tee -a "$REPORT_FILE"
    fi
done

echo "" | tee -a "$REPORT_FILE"

# Footer
cat >> "$REPORT_FILE" << EOF

---

**Report generated by:** \`scripts/docs/generate-metrics-report.sh\`
**Next review:** $(date -v+7d +"%Y-%m-%d" 2>/dev/null || date -d "+7 days" +"%Y-%m-%d")
EOF

echo ""
echo -e "${GREEN}✅ Metrics report generated: $REPORT_FILE${NC}"
echo ""
echo "Next steps:"
echo "  1. Review the report"
echo "  2. Address any missing documentation"
echo "  3. Update orphaned files or add links"
echo "  4. Commit the report to track progress over time"

exit 0
